<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Student Name">
<meta name="author" content="DS303, SP25">
<meta name="author" content="Prof.&nbsp;Amber Camp">
<meta name="dcterms.date" content="2025-02-28">

<title>Assignment 2: Wrapping up regression</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="regression_wrapup_files/libs/clipboard/clipboard.min.js"></script>
<script src="regression_wrapup_files/libs/quarto-html/quarto.js"></script>
<script src="regression_wrapup_files/libs/quarto-html/popper.min.js"></script>
<script src="regression_wrapup_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="regression_wrapup_files/libs/quarto-html/anchor.min.js"></script>
<link href="regression_wrapup_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="regression_wrapup_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="regression_wrapup_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="regression_wrapup_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="regression_wrapup_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#assignment-2-wrapping-up-linear-and-logistic-regression" id="toc-assignment-2-wrapping-up-linear-and-logistic-regression" class="nav-link active" data-scroll-target="#assignment-2-wrapping-up-linear-and-logistic-regression">Assignment 2: Wrapping up linear and logistic regression*</a>
  <ul class="collapse">
  <li><a href="#load-packages" id="toc-load-packages" class="nav-link" data-scroll-target="#load-packages">Load Packages</a></li>
  <li><a href="#load-data" id="toc-load-data" class="nav-link" data-scroll-target="#load-data">Load Data</a></li>
  <li><a href="#question-1-describe-the-data" id="toc-question-1-describe-the-data" class="nav-link" data-scroll-target="#question-1-describe-the-data">Question 1: Describe the data</a></li>
  <li><a href="#question-2-eda" id="toc-question-2-eda" class="nav-link" data-scroll-target="#question-2-eda">Question 2: EDA</a></li>
  <li><a href="#question-3-apply-a-linear-regression" id="toc-question-3-apply-a-linear-regression" class="nav-link" data-scroll-target="#question-3-apply-a-linear-regression">Question 3: Apply a linear regression</a></li>
  <li><a href="#question-4-apply-a-multiple-linear-regression" id="toc-question-4-apply-a-multiple-linear-regression" class="nav-link" data-scroll-target="#question-4-apply-a-multiple-linear-regression">Question 4: Apply a multiple linear regression</a></li>
  <li><a href="#question-5-include-an-interaction" id="toc-question-5-include-an-interaction" class="nav-link" data-scroll-target="#question-5-include-an-interaction">Question 5: Include an interaction</a></li>
  <li><a href="#question-6-compare-models" id="toc-question-6-compare-models" class="nav-link" data-scroll-target="#question-6-compare-models">Question 6: Compare models</a></li>
  <li><a href="#question-7-categorical-predictors" id="toc-question-7-categorical-predictors" class="nav-link" data-scroll-target="#question-7-categorical-predictors">Question 7: Categorical predictors</a></li>
  <li><a href="#question-8-relevel-your-categorical-variable" id="toc-question-8-relevel-your-categorical-variable" class="nav-link" data-scroll-target="#question-8-relevel-your-categorical-variable">Question 8: Relevel your categorical variable</a></li>
  <li><a href="#question-9-apply-a-logistic-regression" id="toc-question-9-apply-a-logistic-regression" class="nav-link" data-scroll-target="#question-9-apply-a-logistic-regression">Question 9: Apply a logistic regression</a></li>
  <li><a href="#question-10-synthesize-the-information" id="toc-question-10-synthesize-the-information" class="nav-link" data-scroll-target="#question-10-synthesize-the-information">Question 10: Synthesize the information</a></li>
  <li><a href="#bonus-stepwise-regression" id="toc-bonus-stepwise-regression" class="nav-link" data-scroll-target="#bonus-stepwise-regression">Bonus: Stepwise Regression</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Assignment 2: Wrapping up regression</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Authors</div>
    <div class="quarto-title-meta-contents">
             <p>Student Name </p>
             <p>DS303, SP25 </p>
             <p>Prof.&nbsp;Amber Camp </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">February 28, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="assignment-2-wrapping-up-linear-and-logistic-regression" class="level1">
<h1>Assignment 2: Wrapping up linear and logistic regression*</h1>
<p>Assignment 2 covers linear and logistic regression models and includes many of the topics we have covered over the entire semester. You will be using <code>palmerpenguins</code> data, which includes a nice variety of continuous and categorical predictors.</p>
<p>To submit this assignment, render this file and save as a pdf. Upload the pdf to Canvas.</p>
<p>*This assignment does not include mixed effects models, but you will be seeing that on another assignment.</p>
<section id="load-packages" class="level2">
<h2 class="anchored" data-anchor-id="load-packages">Load Packages</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lme4)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("palmerpenguins") # install if needed</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(palmerpenguins)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="load-data" class="level2">
<h2 class="anchored" data-anchor-id="load-data">Load Data</h2>
<p>Load the <code>penguins</code> data and examine it below (use <code>summary()</code>, etc.)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>penguins <span class="ot">&lt;-</span> penguins</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(penguins) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      species          island    bill_length_mm  bill_depth_mm  
 Adelie   :152   Biscoe   :168   Min.   :32.10   Min.   :13.10  
 Chinstrap: 68   Dream    :124   1st Qu.:39.23   1st Qu.:15.60  
 Gentoo   :124   Torgersen: 52   Median :44.45   Median :17.30  
                                 Mean   :43.92   Mean   :17.15  
                                 3rd Qu.:48.50   3rd Qu.:18.70  
                                 Max.   :59.60   Max.   :21.50  
                                 NA's   :2       NA's   :2      
 flipper_length_mm  body_mass_g       sex           year     
 Min.   :172.0     Min.   :2700   female:165   Min.   :2007  
 1st Qu.:190.0     1st Qu.:3550   male  :168   1st Qu.:2007  
 Median :197.0     Median :4050   NA's  : 11   Median :2008  
 Mean   :200.9     Mean   :4202                Mean   :2008  
 3rd Qu.:213.0     3rd Qu.:4750                3rd Qu.:2009  
 Max.   :231.0     Max.   :6300                Max.   :2009  
 NA's   :2         NA's   :2                                 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>skimpen <span class="ot">&lt;-</span>  skimr<span class="sc">::</span><span class="fu">skim</span>(penguins)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">view</span>(skimpen)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="question-1-describe-the-data" class="level2">
<h2 class="anchored" data-anchor-id="question-1-describe-the-data">Question 1: Describe the data</h2>
<p>What data is contained in this data set? Describe at least four variables (excluding <code>year</code>), including what they represent and their data type. Lastly, describe whether you think <code>year</code> would be a useful predictor in this data.</p>
<p>This data set contains information on different species of penguins being monitored. The variable island refers to which island the penguin lives on, the year variable tells us what year the penguin was born, then the variables flipper length, bill length, and body mass refer to each characteristic of that penguin. I do not think that year is a good predictor in this data, because the year each penguin is born does not determine their species or their characteristics.</p>
</section>
<section id="question-2-eda" class="level2">
<h2 class="anchored" data-anchor-id="question-2-eda">Question 2: EDA</h2>
<p>Explore your data visually. Create at least two visualizations that show the relationship between <code>flipper_length_mm</code> and its potential predictors.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(penguins, <span class="fu">aes</span>(<span class="at">x =</span> body_mass_g , <span class="at">y =</span> flipper_length_mm)) <span class="sc">+</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="regression_wrapup_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(penguins, <span class="fu">aes</span>(<span class="at">x =</span> species , <span class="at">y =</span> flipper_length_mm)) <span class="sc">+</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="regression_wrapup_files/figure-html/unnamed-chunk-3-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="question-3-apply-a-linear-regression" class="level2">
<h2 class="anchored" data-anchor-id="question-3-apply-a-linear-regression">Question 3: Apply a linear regression</h2>
<p>Fit a simple linear regression model predicting <code>flipper_length_mm</code> from <code>body_mass_g</code>. Interpret the slope and intercept.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(flipper_length_mm <span class="sc">~</span> body_mass_g, <span class="at">data =</span> penguins)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = flipper_length_mm ~ body_mass_g, data = penguins)

Residuals:
     Min       1Q   Median       3Q      Max 
-23.7626  -4.9138   0.9891   5.1166  16.6392 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 1.367e+02  1.997e+00   68.47   &lt;2e-16 ***
body_mass_g 1.528e-02  4.668e-04   32.72   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.913 on 340 degrees of freedom
  (2 observations deleted due to missingness)
Multiple R-squared:  0.759, Adjusted R-squared:  0.7583 
F-statistic:  1071 on 1 and 340 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Interpret your model output in your own words below. Be sure to include a sentence explaining how <code>body_mass_g</code> impacts <code>flipper_length_mm</code> and whether or not the effect is significant.</p>
<p><strong>Answer:</strong> In the model m1 the intercept shows that when body_mass is at 0 flipper length is 1.367mm. The body_mass_g at 1.528 suggests that as body mass increases, the flipper length increases by 1.528. This effect is significant to the data.</p>
</section>
<section id="question-4-apply-a-multiple-linear-regression" class="level2">
<h2 class="anchored" data-anchor-id="question-4-apply-a-multiple-linear-regression">Question 4: Apply a multiple linear regression</h2>
<p>Fit a linear regression model predicting <code>flipper_length_mm</code> from both <code>body_mass_g</code> and <code>bill_length_mm</code>. Interpret the slopes and intercept.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>m2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(flipper_length_mm <span class="sc">~</span> body_mass_g <span class="sc">+</span> bill_length_mm, <span class="at">data =</span> penguins)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = flipper_length_mm ~ body_mass_g + bill_length_mm, 
    data = penguins)

Residuals:
     Min       1Q   Median       3Q      Max 
-21.0989  -4.5520   0.3379   4.8942  16.0953 

Coefficients:
                Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    1.220e+02  2.855e+00  42.715  &lt; 2e-16 ***
body_mass_g    1.305e-02  5.452e-04  23.939  &lt; 2e-16 ***
bill_length_mm 5.492e-01  8.008e-02   6.859 3.31e-11 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.488 on 339 degrees of freedom
  (2 observations deleted due to missingness)
Multiple R-squared:  0.7884,    Adjusted R-squared:  0.7871 
F-statistic: 631.4 on 2 and 339 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Similar to Question 3, interpret the model output in your own words here:</p>
<p><strong>Answer:</strong> Using both body mass and bill length to predict flipper length is statistically significant. bill_length_mm being at 5.492 is associated with having a larger body mass, a larger bill length and a larger flipper length. This means there is a strong, linear relationship between body mass and bill length as predictors of flipper length.</p>
</section>
<section id="question-5-include-an-interaction" class="level2">
<h2 class="anchored" data-anchor-id="question-5-include-an-interaction">Question 5: Include an interaction</h2>
<p>Fit a simple linear regression model predicting <code>flipper_length_mm</code> from <code>body_mass_g,</code> <code>bill_length_mm</code>, and the interaction of the two. Interpret the slopes and intercept.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>m3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(flipper_length_mm <span class="sc">~</span> body_mass_g<span class="sc">:</span>bill_length_mm, <span class="at">data =</span> penguins)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = flipper_length_mm ~ body_mass_g:bill_length_mm, 
    data = penguins)

Residuals:
     Min       1Q   Median       3Q      Max 
-26.3453  -4.6392   0.0653   5.0970  16.1850 

Coefficients:
                            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                1.571e+02  1.313e+00  119.62   &lt;2e-16 ***
body_mass_g:bill_length_mm 2.342e-04  6.752e-06   34.69   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.61 on 340 degrees of freedom
  (2 observations deleted due to missingness)
Multiple R-squared:  0.7797,    Adjusted R-squared:  0.7791 
F-statistic:  1203 on 1 and 340 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Interpret the model output in your own words below. If there was a change in the pattern of significance, try to explain the logic below as well.</p>
<p><strong>Answer:</strong> Model 3 shows that body mass and bill length together is a good predictor of flipper length. In model 1 and 2, they were significant predictors, but when compared to the two variables combined as a predictor, they are less significant. This means so far, the best predictor is body mass and bill length together.</p>
</section>
<section id="question-6-compare-models" class="level2">
<h2 class="anchored" data-anchor-id="question-6-compare-models">Question 6: Compare models</h2>
<p>Compare the models you built in Questions 4 and 5 using <code>anova()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m2,m3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: flipper_length_mm ~ body_mass_g + bill_length_mm
Model 2: flipper_length_mm ~ body_mass_g:bill_length_mm
  Res.Df   RSS Df Sum of Sq      F    Pr(&gt;F)    
1    339 14270                                  
2    340 14853 -1    -583.1 13.852 0.0002315 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<ul>
<li><p>Which is the better model? How do you know?</p>
<ul>
<li><strong>Answer:</strong> The better model is model 2, because the p value is 0.0002, making it highly significant.</li>
</ul></li>
<li><p>Is it possible to compare the models from Questions 3 and 5 using the same method? Why or why not?</p>
<ul>
<li><strong>Answer:</strong> No, it is not possible to compare the models from 3 and 5, because they need a predictor in common. The model from question 3 uses body mass as a predictor, but the model from question 5 uses the combination of body mass and bill length. To compare the models, you would need them to be on levels stacked upon one another, but there isn’t a predictor in common. You could however use the model from 3 and compare it to the model from 4.</li>
</ul></li>
</ul>
</section>
<section id="question-7-categorical-predictors" class="level2">
<h2 class="anchored" data-anchor-id="question-7-categorical-predictors">Question 7: Categorical predictors</h2>
<p>Build a linear model that includes a categorical predictor of your choice. It is fine to stick with dummy coding. Optional: apply a different coding scheme AND interpret the output correctly for +1 extra credit.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>m4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(body_mass_g <span class="sc">~</span> island , <span class="at">data =</span> penguins)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = body_mass_g ~ island, data = penguins)

Residuals:
     Min       1Q   Median       3Q      Max 
-1866.02  -362.90    -6.37   433.98  1583.98 

Coefficients:
                Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)      4716.02      48.47   97.30   &lt;2e-16 ***
islandDream     -1003.11      74.25  -13.51   &lt;2e-16 ***
islandTorgersen -1009.65     100.21  -10.08   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 626.3 on 339 degrees of freedom
  (2 observations deleted due to missingness)
Multiple R-squared:  0.3936,    Adjusted R-squared:   0.39 
F-statistic:   110 on 2 and 339 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ul>
<li><p>What is the reference level of your categorical predictor?</p>
<ul>
<li><strong>Answer:</strong> The island Biscoe.</li>
</ul></li>
<li><p>What is your interpretation of this model output? Address all coefficients.</p>
<ul>
<li><strong>Answer:</strong> The island Dream has a slope of -1003.11, meaning with Biscoe at the reference level, the body mass of penguins on this island is statistically significant, and a penguins body mass is negatively correlated with this island. Meaning penguins on this island weigh less than penguins on Biscoe. The island Torgersen has a slope of -1009.65, also making it statistically significant, and meaning it has the same relationship between it’s penguins body mass as the island Dream does. The intercept being 4716.12 means that is the average weight of a penguin in grams on the Island Biscoe.</li>
</ul></li>
</ul>
</section>
<section id="question-8-relevel-your-categorical-variable" class="level2">
<h2 class="anchored" data-anchor-id="question-8-relevel-your-categorical-variable">Question 8: Relevel your categorical variable</h2>
<p>Relevel your categorical variable so that a <strong>different</strong> level becomes the reference. Then, run the same model you did in Question 7 and interpret the output.</p>
<p>Relevel:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>penguins<span class="sc">$</span>island <span class="ot">&lt;-</span> <span class="fu">relevel</span>(penguins<span class="sc">$</span>island, <span class="at">ref =</span> <span class="st">"Dream"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Apply model from Question 7:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>m4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(body_mass_g <span class="sc">~</span> island , <span class="at">data =</span> penguins)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = body_mass_g ~ island, data = penguins)

Residuals:
     Min       1Q   Median       3Q      Max 
-1866.02  -362.90    -6.37   433.98  1583.98 

Coefficients:
                Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     3712.903     56.248  66.010   &lt;2e-16 ***
islandBiscoe    1003.115     74.249  13.510   &lt;2e-16 ***
islandTorgersen   -6.531    104.193  -0.063     0.95    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 626.3 on 339 degrees of freedom
  (2 observations deleted due to missingness)
Multiple R-squared:  0.3936,    Adjusted R-squared:   0.39 
F-statistic:   110 on 2 and 339 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ul>
<li><p>What is the new reference level of your categorical predictor?</p>
<ul>
<li><strong>Answer:</strong> The new reference level is the Island Dream.</li>
</ul></li>
<li><p>What is your interpretation of this new model output? Address all coefficients.</p>
<ul>
<li><strong>Answer:</strong> This new model shows the avg weight of a penguin on the Island Dream is 3712 g, which is statistically significant. The Island of Biscoe has a slope of 1003, which is statistically significant, and this makes sense because when Biscoe was the reference level, the Island of Dream had a negative slope. What this means is that With the island of Dream at the reference level, there is a positive relationship between the weight of the penguins on Biscoe. The Isle of Torgesen has a negative slope of -6.531, which is not statistically significant. Again, this makes sense because when Biscoe was our reference level, Torgesen and Dream had similar slopes, with Torgesens being only slightly more negative. What this model tells me is that Torgesen and Dream both have a significantly lighter population of penguins on their island than Dream.</li>
</ul></li>
</ul>
</section>
<section id="question-9-apply-a-logistic-regression" class="level2">
<h2 class="anchored" data-anchor-id="question-9-apply-a-logistic-regression">Question 9: Apply a logistic regression</h2>
<p>Apply a logistic regression. Include as many predictor variables as you’d like. Remember that your predicted outcome variable needs to be binary (or categorical with two levels).</p>
<p><br>
Hint: You could use <code>sex</code> or create a binary variable of your own (e.g., Gentoo vs.&nbsp;non-Gentoo) to test your model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>m5 <span class="ot">&lt;-</span> <span class="fu">glm</span>(sex <span class="sc">~</span> species, <span class="at">data =</span> penguins, <span class="at">family =</span> binomial)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m5)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = sex ~ species, family = binomial, data = penguins)

Coefficients:
                  Estimate Std. Error z value Pr(&gt;|z|)
(Intercept)      4.384e-16  1.655e-01   0.000    1.000
speciesChinstrap 1.026e-15  2.936e-01   0.000    1.000
speciesGentoo    5.043e-02  2.470e-01   0.204    0.838

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 461.61  on 332  degrees of freedom
Residual deviance: 461.56  on 330  degrees of freedom
  (11 observations deleted due to missingness)
AIC: 467.56

Number of Fisher Scoring iterations: 3</code></pre>
</div>
</div>
<p>What are your key takeaways from this model?</p>
<p><strong>Answer:</strong> There is no significant relationship between sex and species. This tells me thee is a fairly even spread of sex across the penguin species.</p>
</section>
<section id="question-10-synthesize-the-information" class="level2">
<h2 class="anchored" data-anchor-id="question-10-synthesize-the-information">Question 10: Synthesize the information</h2>
<p>Imagine you’re a biologist studying penguin populations. Which predictors do you think are most important to measure or record in the field to predict flipper length? Why?</p>
<p><strong>Answer:</strong> The most important predictors to measure and record in the field to predict flipper length are body mass, bill length and species. Body mass and bill length together are the strongest predictors for the flipper length, however, the species was a strong predictor for the body mass. I could guess that if I were to run additional models, then species would be the greatest predictor for flipper length.</p>
</section>
<section id="bonus-stepwise-regression" class="level2">
<h2 class="anchored" data-anchor-id="bonus-stepwise-regression">Bonus: Stepwise Regression</h2>
<p>Perform stepwise regression to find the best model for an outcome of your choice. You will likely encounter an error – fixing that error and explaining your findings will earn you +1 extra credit. Show your work.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="do">###to do 3/8</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>According to this stepwise regression, explain how the final model was selected.</p>
<p><strong>Answer:</strong> (Write answer here)</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>